default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
development:
  <<: *default
  database: soliloquence_development
  
test:
  <<: *default
  database: soliloquence_test

production:
  <<: *default
  database: soliloquence_production
  username: soliloquence
  password: <%= ENV['SOLILOQUENCE_DATABASE_PASSWORD'] %>
